# Generated by Django 5.1.2 on 2024-11-04 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=15, help_text="L'utilisateur doit avoir au moins 15 ans", validators=[django.core.validators.MinValueValidator(15)]),
        ),
    ]
